print ('====== Somando ======')
n1 = input('Primeiro Número:')
n2 = input('Segundo Número:')
soma = int(n1) + int(n2)
# print('A soma entre ', n1, ' e ', n2 ,'vale {}'.format(soma))
print ('A soma entre {} e {} vale {}'.format(n1, n2, soma))
